name: Update Film Stats

on:
  schedule:
    - cron: '0 0 */2 * *'  # Run every 2 days at midnight
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4
          
      - name: Update film stats
        run: python scripts/update_film_stats.py
        
      - name: Commit and push if changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add film.html
          git diff --quiet && git diff --staged --quiet || git commit -m "Update film stats automatically"
          git push